name: sumer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_core:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  get:
  ionicons: ^0.2.2
  google_fonts:
  google_sign_in:
  carousel_slider: ^5.0.0
  url_launcher:
  shared_preferences:
  firebase_database:
  badges:
  font_awesome_flutter:
  searchfield: ^1.3.0
  intl_phone_field: ^3.2.0
  emailjs: ^4.0.0
  animated_snack_bar:
  number_paginator: ^0.4.1
  easy_sidemenu: ^0.6.0
  settings_ui:
  dropdown_button2:
  dotted_border: ^2.1.0
  file_picker:
  reorderables: ^0.4.0
  internet_connection_checker: ^1.0.0+1
  flutter_launcher_icons:
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  pdf:
  path_provider:
  share_plus:
  open_file:
  universal_html:
  printing:
  intl:
  webview_flutter:
  dio:
  convex_bottom_bar: ^3.2.0
  connectivity_plus: ^5.0.2
  flutter_inappwebview: ^6.0.0
  shimmer: ^3.0.0
#  flutter_cache_manager:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/SD.png"
flutter:
  uses-material-design: true


  assets:
    - assets/image/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

